version: '3'
services:
  angular-app:
    build:
      context: ./client
    ports:
      - "80:80"
    depends_on:
      - express-server

  express-server:
    build:
      context: ./server
    ports:
      - "3000:3000"

  smtp4dev:
    container_name: dsmtp4dev
    image: rnwood/smtp4dev:latest
    ports:
      - "2525:25" # smtp server
      - "1001:80" # web ui